[package]
name = "orga"
version = "0.1.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"

[dependencies]
error-chain = "0.12.1"
abci2 = { git = "https://github.com/nomic-io/abci2" }
byteorder = "1.3.2"
merk = "1.0.0-alpha.7"

[[example]]
name = "counter"
path = "./examples/counter.rs"
